language: node_js
node_js:
  - "9"
install:
  - npm install -g truffle solium
  - npm install -g ganache-cli
  - npm install
script:
  - npm run solium
  - npm run lint
  - npm run test
after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls
